name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup SSH Access
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_HOST }}
        ssh-port: ${{ secrets.SSH_PORT }}

    - name: Configure Git identity
      run: |
        git config --global user.email "docs@docs-dangit.dev"
        git config --global user.name "Cloudfest Hackathon Cool Kids"
        
    - name: Configure GIT remote
      run: git remote -v
      
    - name: Deploy to Production environment
      run: git push -f production main
