name: Lintint
on: push
jobs:
    lint: #-------------------------------------------
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - name: Check out source code
              uses: actions/checkout@v3

            - name: Install NPM packages
              run: npm ci --include=dev

            - name: Attempt to fix linting errors
              run: |
                  npx eslint --fix .
                  npx prettier --write .
              env:
                  CI: true

            - name: Commit and push if files have changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'chore: lint and format'
                  commit_options: '--no-verify'
                  commit_user_name: 'GitHub Actions'
                  commit_user_email: 'github-actions[bot]@users.noreply.github.com'
                  commit_author: 'GitHub Actions <github-actions[bot]@users.noreply.github.com>'

            - name: Lint and build
              run: |
                  npx eslint --max-warnings 0 .
                  npm run build
              env:
                  CI: true
